server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: administrador-ms
              uri: lb://msAdministrador
              predicates:
                - Path=/api/v1/administradores/**

            - id: asiento-ms
              uri: lb://msAsiento
              predicates:
                - Path=/api/v1/asientos/**, /api/v1/reservas/**

            - id: comprador-ms
              uri: lb://msComprador
              predicates:
                - Path=/api/v1/compradores/**

            - id: direccion-ms
              uri: lb://msDireccion
              predicates:
                - Path=/api/v1/direccion/**

            - id: evento-ms
              uri: lb://msEvento
              predicates:
                - Path=/api/v1/eventos/**

            - id: facturacion-ms
              uri: lb://msFacturacion
              predicates:
                - Path=/api/v1/facturacion/**

            - id: gestionArtistica-ms
              uri: lb://msGestionArtistica
              predicates:
                - Path=/api/v1/artistas/**, /api/v1/managers/** , /api/v1/productoras/**

            - id: login-ms
              uri: lb://msLogin
              predicates:
                - Path=/api/v1/usuarios/**

            - id: ubicacion-ms
              uri: lb://msUbicacion
              predicates:
                - Path=/api/v1/ubicaciones/**

            - id: ventaTicket-ms
              uri: lb://msVentaTicket
              predicates:
                - Path=/api/v1/boletas/** , /api/v1/detalles/** ,/api/v1/tickets/**