server:
  port: 8087

spring:
  application:
    name: msLogin
  datasource:
    url: jdbc:mysql://localhost:3306/login_bd
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
  swagger-ui:
    enabled: true      

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/     